### ISSUE TITLE
Union Problem

### ISSUE THREAD

**Issue by jmwright** [dcowden/cadquery#106]
While trying to round out some unit tests on CQ.py, I got confused by the behavior of union.

The following code results in only one of the two boxes being shown instead of a combination of both.

```python
s = cq.Workplane('XY')
box1 = s.rect(2.0,2.0).extrude(0.5)
box2 = s.rect(1.0,1.0).extrude(1.0)

box1.union(box2.val(), combine=False)
```
Gives:
![union_combine_false](https://cloud.githubusercontent.com/assets/1015439/9307581/401bfd44-44cd-11e5-8377-7b05e274098c.png)

Whereas, setting combine to true gives the other box:
![union_combine_true](https://cloud.githubusercontent.com/assets/1015439/9307672/dfacc3f2-44cd-11e5-87e4-982a72e36a86.png)

However, shouldn't the result of the union operation look something like this:
![union_correct](https://cloud.githubusercontent.com/assets/1015439/9307722/1a4c69cc-44ce-11e5-9781-13695f14e5ee.png)

**Comment by dcowden** [comment]
yeah the semantics of combine=False are not exactly obvious when you are
using a union function, right? I mean union with combine=False doesnt make
any sense.

i cannot immediately explain the behavior-- except to say that its probably
not even be possible to use the combine flag with the union operation....

**Comment by jmwright** [comment]
Ok, thanks. I'll put it on the list of things that need to be investigated.

**Comment by jmwright** [comment]
The following code works as expected, closing this.
```python
import cadquery as cq
from Helpers import show

s = cq.Workplane('XY')
box1 = s.rect(2.0,2.0).extrude(0.5)
box2 = s.rect(1.0,1.0).extrude(1.0)

box3 = box1.union(box2)

show(box3, (204, 204, 204, 0.0))
```
