### ISSUE TITLE
Vector.__hash__()

### ISSUE THREAD

**Issue by galou** [dcowden/cadquery#117]
According to Python documentation (https://docs.python.org/2.7/reference/datamodel.html?highlight=__hash__#object.__hash__),
" If a class defines mutable objects and implements a __cmp__() or __eq__() method, it should not implement __hash__(), since hashable collection implementations require that a object’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket)"

What is the reason why you implemented the __hash__ function?

**Comment by jmwright** [comment]
I think that's a question only @dcowden can answer.

**Comment by jmwright** [comment]
@galou I have removed `__hash_` from `Vector` as of commit 146ecd589bf721976d20784c50ee49a086c6fd4b
