### ISSUE TITLE
How to add 3D TEXT on a CQ's face?

### ISSUE THREAD

**Issue by huskier** [dcowden/cadquery#132]
At present, is it possible to add 3D TEXT on a CQ's face in a easy way?

**Comment by jmwright** [comment]
Not easily that I know of, but have a look at the FreeCAD shapestring "Scripting" example [here](http://www.freecadweb.org/wiki/index.php?title=Draft_ShapeString). There's also an example embedded with the CadQuery FreeCAD module that shows how to use FreeCAD objects from CadQuery code.

Does that help?

**Comment by huskier** [comment]
@jmwright  Thanks. I will look at that code.
