### ISSUE TITLE
CadQuery module start-up and creating a Box automatically

### ISSUE THREAD

**Issue by triplus** [dcowden/cadquery#133]
Hi.

Each time i activate CadQuery WB new Box is added as new document. In my opinion that shouldn't happen and instead user should run the script manually instead if desired.

**Comment by dcowden** [comment]
I do not understand with "CadQuery WB" means, or where the New Box is
coming from. is this referring to the use of the cadquery-freecad-module?

**Comment by triplus** [comment]
Yes you are correct i should have create issue report here:

https://github.com/jmwright/cadquery-freecad-module/issues/72

Sorry for any inconvenience.

**Comment by dcowden** [comment]
No worries!

**Comment by jmwright** [comment]
This got lost in the shuffle. This was fixed in CFM (CadQuery FreeCAD Module).
