### ISSUE TITLE
Repairing STL?

### ISSUE THREAD

**Issue by JamesMilnerUK** [dcowden/cadquery#140]
I am just taking a look through the documentation and in the introduction it says that CadQuery can repair STL files. Is it possible to do things such as fill holes to make STL files watertight? I couldn't see any other reference of repairing files other than in the introduction/README. Thanks in advance.

**Comment by jmwright** [comment]
@JamesMilnerUK That's a new one on me. Can you post a link to where that's mentioned in the intro?

**Comment by JamesMilnerUK** [comment]
@jmwright yeah no problem: https://github.com/dcowden/cadquery#why-cadquery-instead-of-openscad point number 2, about half way through.

**Comment by jmwright** [comment]
Ah, ok. What that's saying is that the OCC CAD kernel is capable of those advanced operations. Those things may not be available in CadQuery though, and STL repair is not. If it's available in OCC it should be possible to get it working in CadQuery, but the implementation would have to be evaluated on a case-by-case basis.
