### ISSUE TITLE
Document New pyparsing Dependency

### ISSUE THREAD

**Issue by jmwright** [dcowden/cadquery#150]
The new selector implementation requires pyparsing. This needs to be documented so that users realize they need to install pyparsing separately. This will likely be more challenging for Windows users.

https://github.com/dcowden/cadquery/pull/148/files

**Comment by dcowden** [comment]
I have added this to requirements.txt, but it is still not documented.

**Comment by jmwright** [comment]
Handled in commit 6371b7cd8ac8e0f3de74c0208b423c1af3470b3b
