### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by dcowden** [dcowden/cadquery#168]
We need a docker image that will allow a user to run CQ without any installation. The image should include CQ and all its dependencies.

This is crucial because while CQ 1.x has no dependencies, CQ 2.x is expected to have several due to new features.

installation of pythonOCC and its OCE and other dependencies is notoriously difficult.  Using the provide conda package is probably the best direction

**Comment by jmwright** [comment]
@dcowden Should we close this issue now due to #205 and open an issue about adding the web service?

**Comment by dcowden** [comment]
Yes, agreed. I forgot this issue was out there
