### ISSUE TITLE
Year End Community Update

### ISSUE THREAD

**Issue by jmwright** [dcowden/cadquery#212]
I've posted a message on the Google Group recapping 2017 and talking about what we'd like to accomplish in 2018.

https://groups.google.com/forum/#!topic/cadquery/fJ1uzOybrKU

**Comment by dcowden** [comment]
Looks great, thanks for communicating that summary!

**Comment by adam-urbanczyk** [comment]
Yes, thanks for compiling this. Let's hope that 2018 is even better!

**Comment by fragmuffin** [comment]
Yeah, very nice!
I look forward to seeing where cadquery goes in the next year, and how I can help.
