### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by adam-urbanczyk** [dcowden/cadquery#246]
It would be nice to test on Windows too. @dcowden @jmwright  could you add this project to https://www.appveyor.com/ ?

**Comment by adam-urbanczyk** [comment]
@dcowden @jmwright  any thoughts on appveyor? I will try it on my fork. I see they have conda preinstalled BTW.

**Comment by dcowden** [comment]
I know little about it so I'm ok with it if you are...

**Comment by jmwright** [comment]
@adam-urbanczyk I'm in the same situation as @dcowden but I'm supportive of trying it. I linked my GitHub account to AppVeyor and set a CadQuery project up (I think). @adam-urbanczyk you were added as a collaborator with administrator privileges, and @dcowden you were added as a team member with admin privileges.

**Comment by dcowden** [comment]
Thanks @jmwright, got the email notification...

**Comment by adam-urbanczyk** [comment]
@jmwright I go the notification too. Not sure what to do with it / how to access the project. I will try first to setup things on my fork using conda / python3.6

**Comment by adam-urbanczyk** [comment]
Solved by #248
