### ISSUE TITLE
User needs to create wires in the correct order

### ISSUE THREAD

**Issue by jmwright** [dcowden/cadquery#260]
This was an [issue originally created](https://github.com/jmwright/cadquery-freecad-module/issues/113) by @Peque on the CadQuery FreeCAD module repo, but I think it's really an issue with the CadQuery API. This could potentially be fixed at the same time as #83 

Also see the discussion [here](https://github.com/jmwright/cadquery-freecad-module/issues/93)

**Comment by zwn** [comment]
There is a solution suggested in https://github.com/jmwright/cadquery-freecad-module/issues/93#issuecomment-353746977. It involves in relying on `Freecad.Face()` to create the face from a list of wires.

**Comment by dcowden** [comment]
This has been closed in favor of the CQ 2.0 implemention at https://github.com/cadquery/cadquery
