### ISSUE TITLE
Incorrect license in README.txt

### ISSUE THREAD

**Issue by fragmuffin** [dcowden/cadquery#276]
The [`README.txt`](https://github.com/dcowden/cadquery/blob/master/README.txt) in the base folder states that `cadquery` is LGPLv3 licensed.

```
License
========

CadQuery is licensed under the terms of the LGPLv3. http://www.gnu.org/copyleft/lesser.html
```

**Comment by jmwright** [comment]
README.txt is outdated by 3 years. I'm wondering if it should just be removed.

**Comment by fragmuffin** [comment]
@jmwright I was wondering about that.
I only found it because I was searching for "GPL" to make sure I'd fixed up my own library.

**Comment by dcowden** [comment]
+1 README.txt should be removed. README.md has the correct license

**Comment by jmwright** [comment]
Done. Thanks for the heads-up @fragmuffin
