### ISSUE TITLE
New CQ GUI available

### ISSUE THREAD

**Issue by adam-urbanczyk** [dcowden/cadquery#280]
I made my CadQuery GUI public today. You can check it out here:

https://github.com/CadQuery/CQ-editor

![screenshot1](https://user-images.githubusercontent.com/13981538/41159853-327fcf6e-6b2e-11e8-9c07-44afb359fa18.png)

**Comment by zignig** [comment]
Nice work Adam. Will have a look and install it on my machine.

**Comment by dcowden** [comment]
This has been closed in favor of the CQ 2.0 implemention at https://github.com/cadquery/cadquery
