### ISSUE TITLE
object_show does not work

### ISSUE THREAD

**Issue by dorianherle** [dcowden/cadquery#290]
On Ubuntu, jupyter-notebook, python 2

When I type

```
import cadquery as cq
result = cq.Workplane("front").box(2.0, 2.0, 0.5)
show_object(result)
```
I get the following error:
NameError                                 Traceback (most recent call last)
<ipython-input-6-4fa5d0e1a19a> in <module>()
      1 result = cq.Workplane("front").box(2.0, 2.0, 0.5)
----> 2 show_object(result)

NameError: name 'show_object' is not defined

**Comment by jmwright** [comment]
@RustyVermeer You have the most experience with Jupyter-Notebook, do you have any thoughts?

**Comment by jmwright** [comment]
@totyped Are you using [CQNB](https://github.com/RustyVermeer/cqnb)?
