### ISSUE TITLE
How to avoid spline to start from origin in cadquery script

### ISSUE THREAD

**Issue by rasunag27** [dcowden/cadquery#311]
Dear CadQuery,

I am working on some tubular structures in which I am using splines and sweep to create the path of points. 

But, the points does not start from origin but from different (x, y) coordinates. When I give spline to those points, the spline does well but it creates a closure by reaching to origin. How do I avoid that.?

Example:

In the below example, I want the spline to start from (1, 2), but it start from (0,0). How to remove the spline from origin?

`import cadquery as cq
from Helpers import show

#### Points we will use to create spline and polyline paths to sweep over
pts = [(1, 2), (2, 1), (4, -1)]

##### Spline path for points ######
path = cq.Workplane("XZ").spline(pts)

show(path)`

I have attached the image link for reference.

[Spline](https://drive.google.com/file/d/1aLy0HonZ6YMIcyhoG-ZMyQ7aUzbJMaS2/view?usp=sharing)

Any leads will be appreciated.

**Comment by jmwright** [comment]
Please post this issue over on the new repository, this one is not really maintained anymore. https://github.com/CadQuery/cadquery
