### ISSUE TITLE
Some Tests Fail

### ISSUE THREAD

**Issue by jmwright** [dcowden/cadquery#56]
As of commit 4d9692e791ab4e035fdb6c3c98759b873d36744d some of the tests fail when running 
```
python runtests.py
```
These tests succeeded the last time I ran them last week. I suspect I introduced a bug with the import fixes that nobody has noticed yet.

**Comment by krasin** [comment]
@jmwright it's ready for a review: https://github.com/dcowden/cadquery/pull/66

The tests output looks like this: https://travis-ci.org/krasin/cadquery/builds/45582528

And thanks for pointing out to the daily PPA repo. That saved a lot of unnecessary work on each build.

**Comment by jmwright** [comment]
@dcowden has merged this and it looks like he's set everything up. The badge is showing passing.

Thanks a bunch for doing this. I'm excited to see it working.

> And thanks for pointing out to the daily PPA repo. 

No problem. That one and the stable PPA are both great to have available.
