### ISSUE TITLE
Request for some more advanced 2D features.

### ISSUE THREAD

**Issue by emdash** [dcowden/cadquery#61]
(edit): I had originally requested some features already covered on the roadmap. I have removed those requests, and will just leave you with the following:

1) Create geometric cross-sections of a solid. This would be useful for exporting drawings to SVG. For example, I might design an enclosure, and then export a cross of the front cover section to an image so that I can import it into an electronics CAD package and use it as a PCB outline.

It would be useful also for creating features that derive from a solid shape. I could take a cross section, project it onto a work plane, and extrude the cross-section.

I have not seen this implemented in any other CAD package.

---

Just want to add that this stuff is actually really cool, and off to a very promising start.

**Comment by emdash** [comment]
One thought for a convention: use ALL_CAPS to denote parameters. I've been doing that in my current project, and it definitely makes the parameters pop out.

**Comment by jmwright** [comment]
> use ALL_CAPS to denote parameters

Even though there aren't technically constants in Python (that I know of), is there a concern that using all caps might conflict with the general programming convention for constants?

**Comment by emdash** [comment]
I suppose it could. If you have people re-using existing python code within CadQuery. However:
- I don't see people doing this very often (especially in a web environment)
- Technically, parameters *are* constants within the script.
- The ALL_CAPS convention comes from C, where ALL_CAPS is used for pre-processor macros (which are sometimes but not always used as constants). 
 - Douglas Crockford makes the point that the ALL_CAPS convention evolved because pre-processor macros don't be have like normal identifiers.
 - I.e. the purpose of ALL_CAPS really just to warn you about a dangerous feature of the environment.
 - I consider use of ALL_CAPS to denote a constant harmful.

**Comment by jmwright** [comment]
I'm closing this because the thread is old and I think everything in it has either been implemented our documented elsewhere.

**Comment by dcowden** [comment]
Thanks for the cleanup
