### ISSUE TITLE
3D Scaling

### ISSUE THREAD

**Issue by emdash** [dcowden/cadquery#62]
Is there any way to scale a 3D object?

**Comment by emdash** [comment]
It would be good to follow up on that at some point...

**Comment by jmwright** [comment]
The function seems to be scaling properly. It scaled each dimension by half (0.5), which just looked strange to me on first glance.

![cq_scale_1](https://cloud.githubusercontent.com/assets/1015439/5640316/f834b096-95f1-11e4-8db3-f34a1efe088f.png)

![cq_scale_2](https://cloud.githubusercontent.com/assets/1015439/5640317/fd0041ee-95f1-11e4-8ce5-5c81f4946cf0.png)
