### ISSUE TITLE
Ideas for Parameter Relations

### ISSUE THREAD

**Issue by emdash** [dcowden/cadquery#63]
Thinking about this, I realized that parameters really do need to be internal to the model. The main reason is that the assumptions about parameter relations are model dependent. For example, I have an open box with a pillar in it that can't be higher than the top edge of the box:

<pre>
Workplane("XY")
.box(w, l, h)
.faces(">Z")
.shell(thickness)
.faces(">Z") # here we the *inside* of the box, but CQ currently wouldn't get this right
.circle(pillarRadius)
.extrude(pillarHeight);
</pre>

If w, l, h, pillarRadius, and pillarHeight, are all parameters, then they have some inherent dependencies. pillarRadius must be < min(w, l) / 2. pillarHeight must be < h. It doesn't make sense to put these outside of the model. If we change the model, these assumptions might change.

***
Streamlined parameter interface
=========================

<pre>
# param function returns a Parameter subclass appropriate for the given default value
# the first argument is the default value, it is required. name / description arguments are all optional.
w = param(1.0)
h = param(1.0)
l = param(1.0)
pillarRadius = param(0.25)
includePillar = param(True)

assert w > 0
assert h > 0
assert l > 0
assert pillarRadius > 0
assert pillarRadius &lt; (min(w, l) / 2)
assert pillarHeight &gt; 0
assert pillarHeight &lt; h
</pre>

How this would work
================

Numerical parameters should override all the arithmetic and comparison operators described in the Python Data Model section of the python documentation. This allows parameters to be used directly as operands in expressions.

In a naive implementation, the assertions present in the code would just execute normally, and would provide direct validation of the input values. A simple parser script can scan the code for statements of the form <id> = param(...) and extract those. Param would not be allowed in any other context.

A more sophisticated implementation can, with a little trickery, produce a graph of parameter relations from this notation. We would need the help of the <code>compiler</code> module to do this, but basically the idea is that assertion statements would be transformed into explict calls to a constraint library:

<code>assert pillarRadius > 0</code> becomes <code>constraints.gt(pillarRadius, 0)</code>
<code>assert pillarRadius < min(w, l)</code> becomes <code>constraints.lt(pillarRadius, constraints.div(constraints.min(w, l)), 2)</code>

The code would then be compiled and executed as normal, with the crucial difference that now we can extract all the parameters in the model and the relationships between them based on the calls to to param() and the constraints.x. We could feed these relationships into a generalized constraint solver, or we could check them directly. We can also construct a gui.

For example, if we determine that a particular numeric constraint has gt and lt constraints applied on it, then we know it is in a closed interval and we can show a slider along with the usual spin button / entry. Whereas if a parameter has a "oneOf" constraint applied to it (translated from the "in" operator), then we can show a combo box.

It might also be possible to recompute the model from changes to the parameters without having to completely re-evaluate the script.

***
There are some places where this could fall down, so I wouldn't be in a rush to adopt this straight-away, I just want to get the idea out there. Limitations I can think of include:

- ternary operator, if statements, and loops
 - handling these correctly would take some care. the gui builder won't know about branches that aren't followed during execution. one possible way out of this is with abstract interpretation, where we follow all branches of a conditional.
 - be much easier to simply disallow calls to param, and assertions, inside of branches and loops, and functions whose expressions themselves depend on parameters.
 - if you think about it, these restrictions make sense. The number of parameters a model takes should probably not depend on the value of any other parameters.
  - except in the case of boolean parameters where it *might* make sense to tie UI visibility / sensitivity.
- there may be other limitations I haven't forseen here.

***

Might make sense to explicitly mark the end of the parameter section and the beginning of the rest of the model. This could be done by, say calling a function, such as <code>endOfParameters()</code> or something along those lines. After this call, it would be an error to attempt to add new paramters or parameter relations. It would be an error for a script to start building a model BEFORE calling this function. This would also allow for easily running a script JUST to validate the parameters, since we can replace the marker with a version that returns immediately.

***
Might make sense to do away with the assertion mechanism, and just use the constraint library explicitly. The main downside would be readability.
***
Other wacky ideas: 
More explicit parameter types. This would be to allow for more interesting gui interaction.
- multi-dimensional paramters <code>x, y = param((0, 0))</code>
- polar parameters <code>y = param(radians(pi))</code>
- list parameters <code>holes = param([(0, 0), (-1, 0), (1, 0)])</code>
  - user would be allowed to edit the list
  - could apply <code>any() / all()</code> functions over the list for validation

**Comment by jmwright** [comment]
This discussion has been moved to the new Google Group since it's long-running and not directly related to an issue in the codebase. https://groups.google.com/forum/?hl=en&nomobile=true#!topic/cadquery/oB3m3JfZxYY

If you're a participant in this discussion, please join the group so that we can continue the discussion there.
