### ISSUE TITLE
line close() problem with workplanes XZ and YZ

### ISSUE THREAD

**Issue by hyOzd** [dcowden/cadquery#92]
Below code works as expected:

    r = cq.Workplane(cq.Plane.XY()).move(5, 2).lineTo(10,0). \
        lineTo(10,10).lineTo(0,10).close().extrude(5)

![cadquery_close](https://cloud.githubusercontent.com/assets/1479166/8124937/7f6e4e7e-10e9-11e5-9b5d-e479f6d0a666.png)

But when I use plane XZ this happens:

    r = cq.Workplane(cq.Plane.XZ()).move(5, 2).lineTo(10,0). \
        lineTo(10,10).lineTo(0,10).close().extrude(5)

![cadquery_close2](https://cloud.githubusercontent.com/assets/1479166/8124940/8afb40e4-10e9-11e5-9a63-6d46f49594df.png)

With Plane.YZ this:
![cadquery_close3](https://cloud.githubusercontent.com/assets/1479166/8124944/9323f2de-10e9-11e5-892d-4003efc4b3e1.png)

It seems that when using a plane other than XY, close() operation takes X or Y coordinate as 0.

**Comment by jmwright** [comment]
It seems that the close function just always assumes you are working in the XY plane.

https://github.com/dcowden/cadquery/blob/master/cadquery/CQ.py#L1639

If I change `self.ctx.firstPoint.y` to `self.ctz.firstPoint.z` and then run your XZ example, it works fine.

@dcowden Is there a reason for the assumption of the XY plane, or is this just a bug?

**Comment by dcowden** [comment]
i think that's just a bug... :\

**Comment by jmwright** [comment]
Is there a better way to handle that then testing what the plane is and then altering which coords get used?

**Comment by hyOzd** [comment]
A ha!

```python
    def _addPendingEdge(self,edge):
        """
            Queues an edge for later combination into a wire.

        :param edge:
        :return:
        """
        self.ctx.pendingEdges.append(edge)

        if self.ctx.firstPoint is None:
            self.ctx.firstPoint = self.plane.toLocalCoords(edge.startPoint())
```

This worked!

**Comment by jmwright** [comment]
All of the tests run fine and so I've pushed this fix to master. Thanks @hyOzd

**Comment by jmwright** [comment]
Fixed in commit 1769eac353469a9023850b7374ace7f557c52e5c

**Comment by dcowden** [comment]
thanks guys for cleaning up my busted code!

**Comment by hyOzd** [comment]
Thank you for creating this software! I love it!
